import { Document, Schema } from "mongoose";
import { IUser } from "./user.interface";
import { IReview } from "./review.interface";
import { EVENT_TYPES } from "../../constants/events.constants";
import { IVendor } from "./vendor.interface";
import { UserRole } from "../../constants/user.constants";

export interface IEvent extends Document {
  type: EVENT_TYPES;
  archived: boolean;
  attendees: IUser[] | Schema.Types.ObjectId[];
  allowedUsers: UserRole[];
  reviews: IReview[];
  eventName: string;
  eventStartDate: Date;
  eventEndDate: Date;
  eventStartTime: string;
  eventEndTime: string;
  registrationDeadline: Date;
  location: string;
  description: string;
  isPassed: boolean;
  price?: number;
  vendors?: { vendor: IVendor | string; RequestData: any }[];
  bazaarAttendees?: { name: string; email: string }[];
  RequestData?: any;
  vendor?: IVendor | string;
  fullAgenda?: string;
  facultyResponsible?: string;
  associatedProfs?: string[];
  budget?: number;
  fundingSource?: string;
  extraResources?: string;
  capacity?: number;
  createdBy: IUser | string;
  createdAt: Date;
  updatedAt: Date;
  stripeProductId?: string;
  stripePriceId?: string;
}
