export enum AdministrationRoleType {
  ADMIN = "admin",
  EVENTS_OFFICE = "eventsOffice"
}

export const ADMIN_PERMISSIONS = [
  "CREATE_ADMIN",
  "DELETE_ADMIN",
  "VERIFY_ROLE",
  "SEND_VERIFICATION",
  "DELETE_COMMENT",
  "BLOCK_USER",
  "VIEW_USERS",
  "MANAGE_PERMISSIONS",
];

export const EVENT_OFFICE_PERMISSIONS = [
  "CREATE_EVENT",
  "UPDATE_EVENT",
  "DELETE_EVENT",
  "ASSIGN_VENDOR",
  "VIEW_EVENT_REGISTRATIONS",
  "APPROVE_VENDOR_UPLOADS",
  "RECEIVE_PROFESSOR_REQUESTS", 
  "APPROVE_PROFESSOR_WORKSHOP",
  "REJECT_PROFESSOR_WORKSHOP",
  "REQUEST_WORKSHOP_EDITS",
];