export enum StaffPosition {
  STAFF = "staff",
  TA = "TA",
  PROFESSOR = "professor"
}

export const PROFESSOR_PERMISSIONS = [
  "EDIT_WORKSHOP_DETAILS",
  "VIEW_MY_WORKSHOPS",
  "VIEW_PARTICIPANTS",
  "VIEW_REMAINING_SPOTS",
  "VIEW_STATUS_REQUESTS",
  "RECEIVE_WORKSHOP_NOTIFICATIONS",
];
